AWSTemplateFormatVersion: "2010-09-09"
Description: VPC Peering LAB Part 2 - Peering

Parameters:

  VPCCIDRRangeA:
   Description: The IP address range for VPC A.
   Type: String
   MinLength: '9'
   MaxLength: '18'
   Default: 10.0.0.0/16
   AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
   ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
   
  VPCCIDRRangeB:
   Description: The IP address range for VPC B.
   Type: String
   MinLength: '9'
   MaxLength: '18'
   Default: 10.1.0.0/16
   AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
   ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  
  VPCCIDRRangeC:
   Description: The IP address range for VPC C.
   Type: String
   MinLength: '9'
   MaxLength: '18'
   Default: 10.2.0.0/16
   AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
   ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

  # PeerRequesterAccountId:
   # Type: String
   # Description: This can be obtained from the outputs from Part 1 of this LAB
   
  # PeerRoleArn:
   # Type: String
   # Description: This can be obtained from the outputs from Part 1 of this LAB  
   
  VPCIdA:
   Type: AWS::EC2::VPC::Id
   Description: Select VPC A
   
  VPCIdB:
   Type: AWS::EC2::VPC::Id
   Description: Select VPC B
   
  VPCIdC:
   Type: AWS::EC2::VPC::Id
   Description: Select VPC C
   
  SubnetA:
   Type: AWS::EC2::Subnet::Id
   Description: Select Subnet A
  
  SubnetB:
   Type: AWS::EC2::Subnet::Id
   Description: Select Subnet B
  
  SubnetC:
   Type: AWS::EC2::Subnet::Id
   Description: Select Subnet C
  
  RouteTableA:
   Type: String
   Description: Input RouteTableA Output from previous Stack
     
  RouteTableB:
   Type: String
   Description: Input RouteTableB Output from previous Stack

  RouteTableC:
   Type: String
   Description: Input RouteTableB Output from previous Stack
   
  
   

   
Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-09d95fab7fff3776c
    us-east-2:
      AMI: ami-026dea5602e368e96
    us-west-1:
      AMI: ami-04e59c05167ea7bd5
    us-west-2:
      AMI: ami-0e34e7b9ca0ace12d
    sa-east-1:
      AMI: ami-0477a95397a9154b3
      
      
Resources:
  vpcPeeringConnectionAwB:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VPCIdA
      PeerVpcId: !Ref VPCIdB
      Tags:
        - Key: Name
          Value: vpcPeeringConnectionAwB
      # PeerOwnerId: !Ref PeerRequesterAccountId
      # PeerRoleArn: !Ref PeerRoleArn
      
  vpcPeeringConnectionBwC:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VPCIdB
      PeerVpcId: !Ref VPCIdC
      Tags:
        - Key: Name
          Value: vpcPeeringConnectionBwC
      # PeerOwnerId: !Ref PeerRequesterAccountId
      # PeerRoleArn: !Ref PeerRoleArn
      
  PeeringRouteAwB:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref VPCCIDRRangeB
      RouteTableId: !Ref RouteTableA
      VpcPeeringConnectionId: !Ref vpcPeeringConnectionAwB
      
  PeeringRouteBwA:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref VPCCIDRRangeA
      RouteTableId: !Ref RouteTableB
      VpcPeeringConnectionId: !Ref vpcPeeringConnectionAwB    

  # SubnetRouteTableAssociationA:
    # Type: 'AWS::EC2::SubnetRouteTableAssociation'
    # Properties:
      # SubnetId: !Ref SubnetA
      # RouteTableId: !Ref PeeringRouteAwB

  PeeringRouteBwC:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref VPCCIDRRangeC
      RouteTableId: !Ref RouteTableB
      VpcPeeringConnectionId: !Ref vpcPeeringConnectionBwC
      
  PeeringRouteCwB:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: !Ref VPCCIDRRangeB
      RouteTableId: !Ref RouteTableC
      VpcPeeringConnectionId: !Ref vpcPeeringConnectionBwC
      
  # SubnetRouteTableAssociationA:
    # Type: 'AWS::EC2::SubnetRouteTableAssociation'
    # Properties:
      # SubnetId: !Ref SubnetB
      # RouteTableId: !Ref PeeringRouteBwC      
      
      
Outputs:

  VPCPeeringConnectionIdAwB:
    Value: !Ref vpcPeeringConnectionAwB    
    
  VPCPeeringConnectionIdBwC:
    Value: !Ref vpcPeeringConnectionBwC     
      